version: '2'

services:
  esbase-new-shiny:
    build: .
    image: ghcr.io/cgi-nrm/esbase-new-shiny:latest
    container_name: esbase-new-shiny
    ports:
      - "3838:3838"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - db_password
    env_file:
      - .env

secrets:
  db_password:
    file:
      db_password.txt
