---
output: 
    pdf_document:
        keep_tex: true
classoption: 
  - landscape
  - a4paper
geometry: 
  - margin=1.5cm
params:
    selected: NA
    biologdata: NA
    provlistas: NA
    provlistas_metas: NA
    db: NA
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{adjustbox}
  - \usepackage{fancyhdr}
  - \usepackage{datetime2}
---

\pagestyle{fancyplain}
\fancyfoot[C]{}
\renewcommand\plainheadrulewidth{.4pt}
\rhead{Genererad \today}
\lhead{Provberedningsrapport}
\rfoot{\hfill \thepage \hfill NRM}

<!-- https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf -->


```{r, echo = FALSE, message = FALSE}
options(knitr.kable.NA = "")
df <- params$biologdata$override
cn <- params$biologdata$colnames

knitr::kable(df, "latex", col.names = cn, linesep = "", booktabs = FALSE, caption = "Biologdata") |>
    kableExtra::kable_styling(latex_options = c("striped", "hold_position"), position = "center") |>
    kableExtra::row_spec(row = 0, angle = 80) |>
    kableExtraExtra_fit_to_page(caption = TRUE)
```

\newpage

```{r, echo = FALSE, message = FALSE}
if (length(params$provlistas) == 0) {
    return()
}

accnr <- params$provlistas[[1]][, "accnr"]
df <- accnr
cnames <- c("Acc.nr.")
ccount <- c(1)

provid_table_cols <- c("accnr", "provid", "aces", "delvikt", "provvikt")
provid_table_cols_pretty <- c("Acc.nr.", "ProvID", "ACES NR", "Delvikt (g)", "Provvikt (g)")

for (n in names(params$provlistas)) {
    cols <- c("provid")
    if (params$provlistas_metas[n, "analyslab", drop = TRUE] == "ACES") {
        cols <- c(cols, "aces")
    }
    if (params$provlistas_metas[n, "homogenat", drop = TRUE]) {
        cols <- c(cols, "delvikt")
    }
    cols <- c(cols, "provvikt")

    df <- dplyr::bind_cols(df, params$provlistas[[n]] |> dplyr::select(dplyr::all_of(cols)))

    cnames <- c(cnames, provid_table_cols_pretty[match(cols, provid_table_cols)])
    ccount <- c(ccount, length(cols))
}

ccount_provname <- ccount
ccount_analystyp <- ccount
ccount_analyslab <- ccount
ccount_analytiker <- ccount
ccount_provtagningsinst <- ccount
ccount_vavnad <- ccount

metas <- params$provlistas_metas |> mutate_at(c("analystyp", "analytiker", "vavnad"), as.numeric)

mega_metas <- (metas |>
               left_join(
                         params$db$analysis_type |> rename_w_prefix("analysis_type."),
                         by = join_by(analystyp == analysis_type.id)) |>
               left_join(
                         params$db$material_type |> rename_w_prefix("material_type."),
                         by = join_by(vavnad == material_type.id)) |>
               left_join(
                         params$db$person |> rename_w_prefix("person."),
                         by = join_by(analytiker == person.id)))

analystyps <- mega_metas |> select(analysis_type.name) |> unlist(use.names = FALSE) |> na_if("") |> replace_na(" ")
analytikers <- (mega_metas |>
                select(person.institution, person.firstname, person.lastname, person.town) |>
                apply(1, paste_collapse) |> unlist(use.names = FALSE) |> na_if("") |> replace_na(" "))
vavnads <- mega_metas |> select(material_type.swe_name) |> unlist(use.names = FALSE) |> na_if("") |> replace_na(" ")

mega_metas <- mega_metas |>
    mutate(analyslab = na_if(analyslab, ""), provtagningsinst = na_if(provtagningsinst, "")) |>
    replace_na(list(analyslab = " ", provtagningsinst = " "))

names(ccount_provname) <- c(" ", names(params$provlistas))
names(ccount_analystyp) <- c(" ", analystyps)
names(ccount_analyslab) <- c(" ", mega_metas[, "analyslab", drop = TRUE])
names(ccount_analytiker) <- c(" ", analytikers)
names(ccount_provtagningsinst) <- c(" ", mega_metas[, "provtagningsinst", drop = TRUE])
names(ccount_vavnad) <- c(" ", vavnads)

if (nrow(df) > 0) {
    knitr::kable(
                 df, "latex", col.names = cnames,
                 linesep = "", booktabs = FALSE, caption = "Provlista") |>
    kableExtra::kable_styling(latex_options = c("striped", "hold_position"), position = "center") |>
    kableExtra::row_spec(row = 0, angle = 80) |>
    kableExtra::add_header_above(ccount_provtagningsinst) |>
    kableExtra::add_header_above(ccount_vavnad) |>
    kableExtra::add_header_above(ccount_analytiker) |>
    kableExtra::add_header_above(ccount_analyslab) |>
    kableExtra::add_header_above(ccount_analystyp) |>
    kableExtra::add_header_above(ccount_provname) |>
    kableExtra::column_spec(grep("provid", colnames(df)), width = "3cm") |>
    kableExtraExtra_fit_to_page(caption = TRUE)
}
```
